Awesome books: a complete website with navigation
sahlminkok/Awesome-Books pull request #3
Opened 2023-05-04 22:41 UTC by sahlminkok

### In this Pull Request we:
1. Modify the Awesome Books application to have A Navigation bar.
2. Add three sections to the page.
3. Use a Single Page Application.

2023-05-04 23:55 UTC, Felix45 requested changes
Hi @sahlminkok & @SamuelTakyiBoateng , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif" width="375px" />

## Highlights :heavy_check_mark: 
- [x] Application is a single-page App
- [x] Good UI design :white_check_mark: 
- [x] Pull request has a descriptive title and summary :white_check_mark: 
- [x] Repository has a professional readme file :white_check_mark:   


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 23:55 UTC, Felix45 commented on script.js
- [ Required ] I think it would be better if you don't disable `Eslint` linter checks since this makes you write code that doesn't follow best JavaScript practices. If you have to disable the linter checks it would be better if you do it from configuration files like `eslintrc.json`  under the `rules` key as shown below.

## Example code
```JavaScript
  "rules": {
    "no-shadow": "off",
    "no-param-reassign": "off",
    "max-classes-per-file": "off",
    "eol-last": "off",
    "import/extensions": [ 1, {
      "js": "always", "json": "always"
    }]
  },
```
In the example code above I've disabled the `max-classes-per-file` Eslint check from the `eslintrc.json` file and not in the source code.

2023-05-04 23:55 UTC, Felix45 commented on style.css
> +} */
- [ Required ] Please consider removing any commented pieces of code from your code base, commented code makes your code base unprofessional and is considered a sign of code that is not clean, please fix this.

2023-05-05 05:08 UTC, binhussen approved these changes
Hi @sahlminkok , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 05:12 UTC, merged